git submodule add https://gitlab-old.doc.ic.ac.uk/g1416302/topics-website.git
git submodule add https://gitlab-old.doc.ic.ac.uk/hopfield-network-jpgsa/hopfield_network_topics.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_spring/javadictionary_pmb14.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_autumn/haskellcalculus_pmb14.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_autumn/haskelllsystems_pmb14.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_autumn/haskellmacroprocessor_pmb14.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_autumn/haskellrecursion_pmb14.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_autumn/haskellquadratic_pmb14.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_spring/assemblermatrixmultiplication_pmb14.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_spring/javaspreadsheet_pmb14.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_spring/sqlfilmqueries_pmb14.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_spring/javadiscreteeventsimulation_pmb14.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_spring/javaturtleinterpreter_pmb14.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_autumn/javarpsls_pmb14.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_spring/javapictureprocessing_pmb14.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_autumn/javaloopsandarrays_pmb14.git
git submodule add https://gitlab-old.doc.ic.ac.uk/lab1415_autumn/javarecursion_pmb14.git
